### PR TITLE
[Jupyter] Adding binder link in order to execute the notebooks

### PR DESCRIPTION
**Pull request by loumalouomega**
Nice job BTW.

Best regards,

Vicente Mataix Ferrándiz

### CODE REVIEW

**Comment by loumalouomega** [comment]
@rambasnet

**Comment by loumalouomega** [comment]
Hello!

**Comment by rambasnet** [comment]
Thank you for the feedback and pull request. I've not had a chance to verify your suggested update...

**Comment by loumalouomega** [comment]
I closed due to inactivity, let me one sec

**Comment by loumalouomega** [comment]
These are the changes:

imagen

You can try it out with: https://mybinder.org/v2/gh/rambasnet/CPP-Fundamentals/HEAD?filepath=Ch00-TableOfContents.ipynb

But I think until you don't merge will not work, because the environment.yml is not defined

**Comment by loumalouomega** [comment]
Hello @rambasnet

**Comment by rambasnet** [comment]
Hi @loumalouomega, I get
Screen Shot 2021-05-11 at 8 48 04 AM
 error while trying to launch the notebooks on mybinder.org: [https://mybinder.org/v2/gh/rambasnet/CPP-Fundamentals/HEAD?filepath=Ch00-TableOfContents.ipynb](https://mybinder.org/v2/gh/rambasnet/CPP-Fundamentals/HEAD?filepath=Ch00-TableOfContents.ipynb )

**Comment by loumalouomega** [comment]
Strange, let me check

**Comment by loumalouomega** [comment]
> Hi @loumalouomega, I get
> Screen Shot 2021-05-11 at 8 48 04 AM
> error while trying to launch the notebooks on mybinder.org: [mybinder.org/v2/gh/rambasnet/CPP-Fundamentals/HEAD?filepath=Ch00-TableOfContents.ipynb](https://mybinder.org/v2/gh/rambasnet/CPP-Fundamentals/HEAD?filepath=Ch00-TableOfContents.ipynb)

Until this is not merged, the file environment.yml does not exist in the master. Let me generate the link for the branch

**Comment by loumalouomega** [comment]
> > Hi @loumalouomega, I get
> > Screen Shot 2021-05-11 at 8 48 04 AM
> > error while trying to launch the notebooks on mybinder.org: [mybinder.org/v2/gh/rambasnet/CPP-Fundamentals/HEAD?filepath=Ch00-TableOfContents.ipynb](https://mybinder.org/v2/gh/rambasnet/CPP-Fundamentals/HEAD?filepath=Ch00-TableOfContents.ipynb)
> 
> Until this is not merged, the file environment.yml does not exist in the master. Let me generate the link for the branch

Well, i can't as i removed my repo..., I can create a new copy

**Comment by loumalouomega** [comment]
> > > Hi @loumalouomega, I get
> > > Screen Shot 2021-05-11 at 8 48 04 AM
> > > error while trying to launch the notebooks on mybinder.org: [mybinder.org/v2/gh/rambasnet/CPP-Fundamentals/HEAD?filepath=Ch00-TableOfContents.ipynb](https://mybinder.org/v2/gh/rambasnet/CPP-Fundamentals/HEAD?filepath=Ch00-TableOfContents.ipynb)
> > 
> > 
> > Until this is not merged, the file environment.yml does not exist in the master. Let me generate the link for the branch
> 
> Well, i can't as i removed my repo..., I can create a new copy

See: https://gitlab.inria.fr/vicente.mataix/CPP-Fundamentals

https://mybinder.org/v2/git/https%3A%2F%2Fgitlab.inria.fr%2Fvicente.mataix%2FCPP-Fundamentals/HEAD?filepath=Ch00-TableOfContents.ipynb

**Comment by rambasnet** [comment]
@loumalouomega Thanks for the update!

**Comment by loumalouomega** [comment]
You are welcome

**Pull request merged**
